services:
  - type: web
    name: Minimax-api
    env: python
    region: oregon  # Puedes usar frankfurt o ohio si estás en Europa o USA
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000  # Render ignora esto, pero algunas apps lo requieren

